name: CI

on:
  push:
    tags:
    - 'devstack*'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build packer
      run: ./.github/workflows/devstack-build.sh
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: true
    - name: Upload qcow2
      id: upload-release-asset-qcow2
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        # FIXME:
        asset_path: ./output/devstack/ubuntu-2004-kube-v1.18.15.qcow2
        asset_name: devstack-2004.qcow2
        asset_content_type: application/zip
    - name: Upload vmdk
      id: upload-release-asset-vmdk
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        # FIXME
        asset_path: ./output/devstack/ubuntu-2004-kube-v1.18.15.vmdk
        asset_name: devstack-2004.vmdk
        asset_content_type: application/zip
